export const LOCATION_AUTOCOMPLETE = 'LOCATION_AUTOCOMPLETE';

export const GET_CURRENT_WEATHER = 'GET_CURRENT_WEATHER';

export const FIVE_DAY_DAILY_FORECAST = 'FIVE_DAY_DAILY_FORECAST';

export const MOVE_TO_HOMEPAGE = 'MOVE_TO_HOMEPAGE';

export const GET_CURRENT_WEATHER_BY_LOCATION = 'GET_CURRENT_WEATHER_BY_LOCATION';